### ISSUE TITLE
Implement text clob parsing

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-rust#125]
This can largely piggy back on the parser for `string`, which supports both short and long-form strings. The main differences are:

* Long-form `string`s allow comments to appear between `'''`-delimited segments while `clob`s [do not permit comments anywhere in the body](https://amzn.github.io/ion-docs/docs/spec.html#clob):

> In the text format, clob values use similar syntax to blob, but the data between braces must be one string. The string may only contain legal 7-bit ASCII characters, using the same escaping syntax as string and symbol values. This guarantees that the value can be transmitted unscathed while remaining generally readable (at least for western language text). Like blobs, clobs disallow comments everywhere within the value.

* Clobs only allow displayable ASCII characters and `\n` to be included in their encoding as-is. All other characters [must be written as unicode escape sequences](https://amzn.github.io/ion-docs/docs/stringclob.html#ion-clob):

> The rules for the quoted strings within a clob follow the similarly to the string type, with the following exceptions. Unicode newline characters in long strings and all verbatim ASCII characters are interpreted as their ASCII octet values. Non-printable ASCII and non-ASCII Unicode code points are not allowed un-escaped in the string bodies. Furthermore, the following table describes the clob string escape sequences that have direct octet replacement for both all strings.

**Comment by desaikd** [comment]
This has been fixed with #130
