### ISSUE TITLE
Implement `PartialEq`/`Eq` for `SymbolToken`, `Sequrence`, `Struct `

### ISSUE THREAD

**Issue by desaikd** [amzn/ion-rust#149]
Implement `PartiEq`/ `Eq` for `SymbolToken`, `Sequrence`, `Struct` for easier unit testing. For `Struct` and `Sequence` it would mean we have to add `PartialEq` / `Eq` for `OwnedElement`.

**Comment by almann** [comment]
Related to #114.

**Comment by desaikd** [comment]
This issue is fixed with #152
