### ISSUE TITLE
`OwnedStruct` `PartialEq` Does Not Use `no_text_fields`

### ISSUE THREAD

**Issue by desaikd** [amzn/ion-rust#161]
*Related to #152*
It seems we need to add separate tests for `no_text_fields` in `OwnedStruct`. It might also lead to a change in `PartialEq` for `OwnedStruct`.

**Comment by almann** [comment]
I changed the title, because the implementation doesn't use `no_text_fields` and therefore has a bug.  The testing is important, but the fact that it is a bug is more so.
