### ISSUE TITLE
`OwnedSymbolToken` `PartialEq` Should Be Transitive

### ISSUE THREAD

**Issue by almann** [amzn/ion-rust#170]
`OwnedSymbolToken` implementation of `PartialEq` does not appear to be transitive, this should be fixed (or at least tests added to verify see #153).

![image](https://user-images.githubusercontent.com/503506/114250486-b9e39580-9952-11eb-952b-b79f543e520a.png)

_Originally posted by @almann in https://github.com/amzn/ion-rust/pull/163#issuecomment-817029438_

**Comment by desaikd** [comment]
This has been addressed with #181 and merged into main.
