### ISSUE TITLE
Make test case code generic for `Owned`/`BorrowedElement`

### ISSUE THREAD

**Issue by desaikd** [amzn/ion-rust#185]
Currently the test case code for both `Owned`/`BorrowedElement` are kind of a copy/paste. We need to work on a generic implementation to allow both to be tested  together in a single test case code.

Also, for this issue to be fixed it also needs to address #184 as a prerequisite to this. 

After this issue is fixed we can work on creating generic test cases for `Owend`/`BorrowedElement` defined with issue #186

**Comment by almann** [comment]
Related to #157 and #183.

**Comment by desaikd** [comment]
This issue is fixed with #206
