### ISSUE TITLE
Make test cases generic for `Owned`/`BorrowedElement`

### ISSUE THREAD

**Issue by desaikd** [amzn/ion-rust#186]
Currently the test cases for both `Owned`/`BorrowedElement` are kind of a copy/paste. We need to work on a generic implementation to allow both to be tested  together with same set of test cases in order to work with generic test case code defined in #185.

**Comment by almann** [comment]
Related to #157 and #183.

**Comment by desaikd** [comment]
This issue is fixed with #206
