### ISSUE TITLE
Add Doc Test Examples for `Loader` API

### ISSUE THREAD

**Issue by almann** [amzn/ion-rust#208]
After publishing `ion-rs` 0.4.0, I noticed that we should have some examples of how to use the APIs in the main docs.  We should also clean up the API documentation for it.

**Comment by almann** [comment]
> @almann i am a newbie to open source contribution, do you mind if i pick up this issue?

Appreciate you reaching out--I had started this last night actually in this [commit][1] so there is not too much left to do there.  If you'd like a good first issue, I think #209 looks pretty straightforward.

[1]: https://github.com/almann/ion-rust/commit/f56a89f297500238a32259f27c5bd66221ef4c8b

**Comment by SivaTharun** [comment]
> 
> 
> > @almann i am a newbie to open source contribution, do you mind if i pick up this issue?
> 
> Appreciate you reaching out--I had started this last night actually in this [commit](https://github.com/almann/ion-rust/commit/f56a89f297500238a32259f27c5bd66221ef4c8b) so there is not too much left to do there. If you'd like a good first issue, I think #209 looks pretty straightforward.

Thanks @almann for the reference
