### ISSUE TITLE
Add an `IonEq` Trait for Ion Data Model Equivalence

### ISSUE THREAD

**Issue by almann** [amzn/ion-rust#220]
Things like `PartialEq` cannot be implemented against the Ion data model for things like `SymbolToken` because of symmetry concerns, but also structural equality around numerics (e.g. `NaN`) cannot be done with `PartialEq` as well.  We should add a trait to support these kinds of comparisons.

**Comment by zslayton** [comment]
We also need `IonEq` for `Decimal`. Currently, `cmp` considers `-0` to not be equal to `0` because they're not Ion-equivalent. This isn't correct mathematically, however. `cmp` should consider them equal while `IonEq` would consider them different.

**Comment by zslayton** [comment]
See also: #127, which I have closed as a dup of this.
