### ISSUE TITLE
`Timestamp` Serialization Should Not Be Fixed to Nanoseconds

### ISSUE THREAD

**Issue by almann** [amzn/ion-rust#274]
#272 ports some internal code to APIs, part of this is a TODO to make `Timestamp` serialization to be not fixed to nanoseconds.

When searching for prior issues, I found #17, but I am not sure if that is different or already resolved (since it indicates *skipping* fractional seconds).  @zslayton can probably confirm this.

---

So this means that if there exists sub-second precision, that precision is always nine digits (i.e. nanoseconds)?

_Originally posted by @almann in https://github.com/amzn/ion-rust/pull/272#discussion_r643643079_

**Comment by zslayton** [comment]
Prior to #272, the binary reader/writer only worked with `DateTime<_>`, which represents its fractional seconds as nanoseconds. Both reading and writing had a `TODO` to support other levels of precision.

Now that we're supporting reading and writing `Timestamp`s (which natively support setting/getting the precision), assuming nanoseconds on this code path no longer makes sense.
