### ISSUE TITLE
VarInt and negative zero

### ISSUE THREAD

**Issue by marcbowes** [amzn/ion-rust#278]
https://github.com/amzn/ion-rust/blob/d1768e8f18a11695181a16e379e426780d865b39/src/binary/timestamp.rs#L46-L48
https://github.com/amzn/ion-rust/blob/d1768e8f18a11695181a16e379e426780d865b39/src/binary/var_int.rs#L78

I think that "unknown timezone" is meant to be represented by negative zero, and i64 doesn't actually support that:

```
    let value: i64 = -0;

    println!("{}", value);

    println!(
        "{}",
        match value.is_negative() {
            true => "true",
            _ => "false",
        }
    );

    println!("{:02x?}", value.to_be_bytes());
```

```
0
false
[00, 00, 00, 00, 00, 00, 00, 00]
```

**Comment by almann** [comment]
Yeah, we need to treat this case explicitly, either adding `VarInt::write_negative_zero()` or something of that ilk.
