### ISSUE TITLE
Decimal comparator is incorrect

### ISSUE THREAD

**Issue by sunpeaksfivemile** [amzn/ion-rust#305]
Example test that fails:

    #[test]
    fn test_decimal_comparison() {
        let left = BigDecimal::from_str("-100.0").unwrap();
        let right = BigDecimal::from_str("-99.999999999").unwrap();
        assert_eq!(Ordering::Less, left.partial_cmp(&right).unwrap());

        let left: Decimal = left.into();
        let right: Decimal = right.into();
        assert_eq!(Ordering::Less, left.partial_cmp(&right).unwrap()); // panics
    }

**Comment by zslayton** [comment]
Good find. This is indeed peculiar; if I rewrite the assert to be inverted, it passes:

```rust
// Original version
assert_eq!(Ordering::Less, left.partial_cmp(&right).unwrap()); // panics
assert_eq!(Ordering::Greater, right.partial_cmp(&left).unwrap()); // works
```

I think it's related to this bit of code:

https://github.com/amzn/ion-rust/blob/a1c8b03e70a0e13d59cc3424198c3149692bdc7b/src/types/decimal.rs#L84-L90

The `else` calls the helper function with the parameters flipped, so the result should probably have a negation.
