### ISSUE TITLE
Support larger primitive and/or arbitrary sized Integers

### ISSUE THREAD

**Issue by robcalhounjr** [amzn/ion-rust#343]
There is currently no support for reading or writing `u64`, `i128` or `u128` integers, nor for reading or writing arbitrary size integers. The impact of this is that currently users cannot read or write the full range of integers supported by the ion value system.

A related note is that the existing implementation always consumes memory for an `i64` even if the actual int can fit a shorter primitive type.

**Comment by zslayton** [comment]
> There is currently no support for reading or writing u64, i128 or u128 integers, nor for reading or writing arbitrary size integers. The impact of this is that currently users cannot read or write the full range of integers supported by the ion value system.

This has been fixed by #372.

> A related note is that the existing implementation always consumes memory for an i64 even if the actual int can fit a shorter primitive type.

I'm not sure what "consumes memory for an i64" refers to here. This code snipped will read an Ion int as an `i64` and then cast it to an `i8` if it's small enough. 

```rust
let small_int: i8 = reader.read_i64()?.try_into()?;
```

The `i64` only exists (briefly) on the stack. Could you expand on what you're looking for?

**Comment by robcalhounjr** [comment]
My primary concern was the support for arbitrary sized integers. If that is implemented then the issue may be closed.

I agree that allocating for an i64 purely on the stack is not really a concern.
