### ISSUE TITLE
Create new crates.io release

### ISSUE THREAD

**Issue by landonxjames** [amzn/ion-rust#367]
The last release on crates.io is 4 months old and there have been several features implemented since then. Please push a new release to crates.io with the latest updates.

**Comment by zslayton** [comment]
Sure thing. Once the pending pull requests have landed I'll cut another dev release.

**Comment by zslayton** [comment]
[`ion-rust` v0.9.0](https://github.com/amzn/ion-rust/releases/tag/v0.9.0) is now available.
