### ISSUE TITLE
The Ion spec says that all timestamps are specific moments in time

### ISSUE THREAD

**Issue by jobarr-amzn** [amzn/ion-rust#385]
This comment in `timestamp.rs` says that we can't compare timestamps with different precisions:
https://github.com/amzn/ion-rust/blob/791efb447ef0e1d1bd26787c7efa9cf9b77734ac/src/types/timestamp.rs#L320-L325

That makes sense to me, but the [Ion spec on timestamps](https://amzn.github.io/ion-docs/docs/spec.html#timestamp) has this example:
```plain
2007-01-01T00:00-00:00           // Happy New Year in UTC, unknown local offset
2007-01-01                       // The same instant, with days precision, unknown local offset
2007-01-01T                      //    The same value, different syntax.
2007-01T                         // The same instant, with months precision, unknown local offset
2007T                            // The same instant, with years precision, unknown local offset
```

If these are all the same instant, they can be compared. The spec is wrong, or this implementation is. Personally and ignorant of the implications, I'd rather call the spec wrong because my intuition is that a specific moment in time only known as `2007T` could be any one of 31556926 seconds whereas `2007-01-01T00:00` is a specific one of them. 

I have not thought deeply about this, but these different values can't both be the same instant and incomparable.

**Comment by zslayton** [comment]
This is related to #127, #381, and #209.

Ultimately, the comment in `timestamp.rs` is wrong.

>  I'd rather call the spec wrong because my intuition is that a specific moment in time only known as 2007T could be any one of 31556926 seconds whereas 2007-01-01T00:00 is a specific one of them.

I agree that this is more intuitive; however, a `timestamp`'s precision is analogous to a `decimal`'s precision. Just as `1.1` and `1.10` are mathematically equivalent but not Ion-equivalent, `2022T` and `2022-01-01` are the same point in time but not Ion-equivalent. See [the Ion Schema spec section `Range<Timestamp>`](https://amzn.github.io/ion-schema/docs/spec.html#rangetimestamp) for more information.

I intend to make `Timestamp`'s current behavior the definition of `ion_eq`, freeing up `eq`/`==` to compare timestamps as points in time. We can also define a precision-agnostic ordering for `PartialOrd`/`Ord`.
